import type { CoverArt } from "@/lib/content/types";

/** Raster cover for lock-screen artwork (generated by `pnpm covers:png`). */
export function coverPngUrl(cover: CoverArt): string {
  return `/covers/${cover.symbol ?? "moon"}-${cover.accent.replace("#", "").toLowerCase()}.png`;
}
